

build: .build-impl
	@echo "Build Successful!"


clean: .clean-impl
	@echo "Clean Done!"

# include project build rules makefile
include build_support/Makefile-impl.mk

# include project make variables
include build_support/Makefile-var.mk
